<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="LAPTOP-F72VL5U5" ignored="1" name="TestOnChrome" tests="7" failures="3" timestamp="2020-05-03T01:26:36 EDT" time="81.218" errors="0">
  <testcase name="test1" time="6.327" classname="test.testCases.SearchPageTestCases"/>
  <testcase name="testF1" time="0.007" classname="test.testCases.retryFailedDemo">
    <skipped/>
  </testcase> <!-- testF1 -->
  <testcase name="testF1" time="0.003" classname="test.testCases.retryFailedDemo">
    <skipped/>
  </testcase> <!-- testF1 -->
  <testcase name="testF1" time="0.003" classname="test.testCases.retryFailedDemo">
    <skipped/>
  </testcase> <!-- testF1 -->
  <testcase name="testF1" time="0.004" classname="test.testCases.retryFailedDemo">
    <failure type="java.lang.AssertionError" message="expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: expected [false] but found [true]
at test.testCases.retryFailedDemo.testF1(retryFailedDemo.java:13)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
... Removed 22 stack frames]]>
    </failure>
  </testcase> <!-- testF1 -->
  <testcase name="testF2" time="0.003" classname="test.testCases.retryFailedDemo">
    <failure type="java.lang.ArithmeticException" message="/ by zero">
      <![CDATA[java.lang.ArithmeticException: / by zero
at test.testCases.retryFailedDemo.testF2(retryFailedDemo.java:20)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
... Removed 18 stack frames]]>
    </failure>
  </testcase> <!-- testF2 -->
  <testcase name="testF3" time="0.003" classname="test.testCases.retryFailedDemo">
    <failure type="java.lang.AssertionError" message="expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: expected [false] but found [true]
at test.testCases.retryFailedDemo.testF3(retryFailedDemo.java:28)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
... Removed 22 stack frames]]>
    </failure>
  </testcase> <!-- testF3 -->
  <testcase name="@BeforeSuite setupBrowser" time="0.0" classname="test.testCases.BaseTest">
    <ignored/>
  </testcase> <!-- @BeforeSuite setupBrowser -->
</testsuite> <!-- TestOnChrome -->
