<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="3" ignored="1" retried="3" total="8" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Suite" duration-ms="81218" started-at="2020-05-03T01:25:15 EDT" finished-at="2020-05-03T01:26:36 EDT">
    <groups>
      <group name="classOneTests">
        <method signature="SearchPageTestCases.test1()[pri:0, instance:test.testCases.SearchPageTestCases@77f80c04]" name="test1" class="test.testCases.SearchPageTestCases"/>
      </group> <!-- classOneTests -->
      <group name="regression">
        <method signature="SearchPageTestCases.test1()[pri:0, instance:test.testCases.SearchPageTestCases@77f80c04]" name="test1" class="test.testCases.SearchPageTestCases"/>
      </group> <!-- regression -->
      <group name="sanity">
        <method signature="SearchPageTestCases.test1()[pri:0, instance:test.testCases.SearchPageTestCases@77f80c04]" name="test1" class="test.testCases.SearchPageTestCases"/>
      </group> <!-- sanity -->
    </groups>
    <test name="TestOnChrome" duration-ms="81218" started-at="2020-05-03T01:25:15 EDT" finished-at="2020-05-03T01:26:36 EDT">
      <class name="test.testCases.retryFailedDemo">
        <test-method status="PASS" signature="SetupClassPreRequisite()[pri:0, instance:test.testCases.retryFailedDemo@1dac5ef]" name="SetupClassPreRequisite" is-config="true" duration-ms="0" started-at="2020-05-03T01:25:29 EDT" finished-at="2020-05-03T01:25:29 EDT">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- SetupClassPreRequisite -->
        <test-method status="PASS" signature="createDriverInstance(java.lang.String)[pri:0, instance:test.testCases.retryFailedDemo@1dac5ef]" name="createDriverInstance" is-config="true" duration-ms="4372" started-at="2020-05-03T01:25:29 EDT" finished-at="2020-05-03T01:25:33 EDT">
          <params>
            <param index="0">
              <value>
                <![CDATA[chrome]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- createDriverInstance -->
        <test-method status="SKIP" signature="testF1()[pri:0, instance:test.testCases.retryFailedDemo@1dac5ef]" name="testF1" duration-ms="7" retried="true" started-at="2020-05-03T01:25:33 EDT" finished-at="2020-05-03T01:25:33 EDT">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [false] but found [true]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [false] but found [true]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.failNotEquals(Assert.java:969)
at org.testng.Assert.assertFalse(Assert.java:65)
at org.testng.Assert.assertFalse(Assert.java:75)
at test.testCases.retryFailedDemo.testF1(retryFailedDemo.java:13)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:597)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at org.testng.TestRunner.privateRun(TestRunner.java:766)
at org.testng.TestRunner.run(TestRunner.java:587)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:28)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:425)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:68)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testF1 -->
        <test-method status="PASS" signature="closeBrowser()[pri:0, instance:test.testCases.retryFailedDemo@1dac5ef]" name="closeBrowser" is-config="true" duration-ms="805" started-at="2020-05-03T01:25:33 EDT" finished-at="2020-05-03T01:25:34 EDT">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeBrowser -->
        <test-method status="PASS" signature="createDriverInstance(java.lang.String)[pri:0, instance:test.testCases.retryFailedDemo@1dac5ef]" name="createDriverInstance" is-config="true" duration-ms="4389" started-at="2020-05-03T01:25:34 EDT" finished-at="2020-05-03T01:25:38 EDT">
          <params>
            <param index="0">
              <value>
                <![CDATA[chrome]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- createDriverInstance -->
        <test-method status="SKIP" signature="testF1()[pri:0, instance:test.testCases.retryFailedDemo@1dac5ef]" name="testF1" duration-ms="3" retried="true" started-at="2020-05-03T01:25:38 EDT" finished-at="2020-05-03T01:25:38 EDT">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [false] but found [true]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [false] but found [true]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.failNotEquals(Assert.java:969)
at org.testng.Assert.assertFalse(Assert.java:65)
at org.testng.Assert.assertFalse(Assert.java:75)
at test.testCases.retryFailedDemo.testF1(retryFailedDemo.java:13)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:597)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:213)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at org.testng.TestRunner.privateRun(TestRunner.java:766)
at org.testng.TestRunner.run(TestRunner.java:587)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:28)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:425)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:68)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testF1 -->
        <test-method status="PASS" signature="closeBrowser()[pri:0, instance:test.testCases.retryFailedDemo@1dac5ef]" name="closeBrowser" is-config="true" duration-ms="843" started-at="2020-05-03T01:25:38 EDT" finished-at="2020-05-03T01:25:39 EDT">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeBrowser -->
        <test-method status="PASS" signature="createDriverInstance(java.lang.String)[pri:0, instance:test.testCases.retryFailedDemo@1dac5ef]" name="createDriverInstance" is-config="true" duration-ms="4656" started-at="2020-05-03T01:25:39 EDT" finished-at="2020-05-03T01:25:44 EDT">
          <params>
            <param index="0">
              <value>
                <![CDATA[chrome]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- createDriverInstance -->
        <test-method status="SKIP" signature="testF1()[pri:0, instance:test.testCases.retryFailedDemo@1dac5ef]" name="testF1" duration-ms="3" retried="true" started-at="2020-05-03T01:25:44 EDT" finished-at="2020-05-03T01:25:44 EDT">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [false] but found [true]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [false] but found [true]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.failNotEquals(Assert.java:969)
at org.testng.Assert.assertFalse(Assert.java:65)
at org.testng.Assert.assertFalse(Assert.java:75)
at test.testCases.retryFailedDemo.testF1(retryFailedDemo.java:13)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:597)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:213)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at org.testng.TestRunner.privateRun(TestRunner.java:766)
at org.testng.TestRunner.run(TestRunner.java:587)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:28)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:425)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:68)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testF1 -->
        <test-method status="PASS" signature="closeBrowser()[pri:0, instance:test.testCases.retryFailedDemo@1dac5ef]" name="closeBrowser" is-config="true" duration-ms="2971" started-at="2020-05-03T01:25:44 EDT" finished-at="2020-05-03T01:25:47 EDT">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeBrowser -->
        <test-method status="PASS" signature="createDriverInstance(java.lang.String)[pri:0, instance:test.testCases.retryFailedDemo@1dac5ef]" name="createDriverInstance" is-config="true" duration-ms="11151" started-at="2020-05-03T01:25:47 EDT" finished-at="2020-05-03T01:25:58 EDT">
          <params>
            <param index="0">
              <value>
                <![CDATA[chrome]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- createDriverInstance -->
        <test-method status="FAIL" signature="testF1()[pri:0, instance:test.testCases.retryFailedDemo@1dac5ef]" name="testF1" duration-ms="4" started-at="2020-05-03T01:25:58 EDT" finished-at="2020-05-03T01:25:58 EDT">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [false] but found [true]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [false] but found [true]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.failNotEquals(Assert.java:969)
at org.testng.Assert.assertFalse(Assert.java:65)
at org.testng.Assert.assertFalse(Assert.java:75)
at test.testCases.retryFailedDemo.testF1(retryFailedDemo.java:13)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:597)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:213)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at org.testng.TestRunner.privateRun(TestRunner.java:766)
at org.testng.TestRunner.run(TestRunner.java:587)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:28)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:425)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:68)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testF1 -->
        <test-method status="PASS" signature="closeBrowser()[pri:0, instance:test.testCases.retryFailedDemo@1dac5ef]" name="closeBrowser" is-config="true" duration-ms="26546" started-at="2020-05-03T01:25:58 EDT" finished-at="2020-05-03T01:26:24 EDT">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeBrowser -->
        <test-method status="PASS" signature="createDriverInstance(java.lang.String)[pri:0, instance:test.testCases.retryFailedDemo@1dac5ef]" name="createDriverInstance" is-config="true" duration-ms="5260" started-at="2020-05-03T01:26:24 EDT" finished-at="2020-05-03T01:26:30 EDT">
          <params>
            <param index="0">
              <value>
                <![CDATA[chrome]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- createDriverInstance -->
        <test-method status="FAIL" signature="testF2()[pri:0, instance:test.testCases.retryFailedDemo@1dac5ef]" name="testF2" duration-ms="3" started-at="2020-05-03T01:26:30 EDT" finished-at="2020-05-03T01:26:30 EDT">
          <exception class="java.lang.ArithmeticException">
            <message>
              <![CDATA[/ by zero]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.ArithmeticException: / by zero
at test.testCases.retryFailedDemo.testF2(retryFailedDemo.java:20)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:597)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at org.testng.TestRunner.privateRun(TestRunner.java:766)
at org.testng.TestRunner.run(TestRunner.java:587)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:28)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:425)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:68)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.ArithmeticException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testF2 -->
        <test-method status="PASS" signature="closeBrowser()[pri:0, instance:test.testCases.retryFailedDemo@1dac5ef]" name="closeBrowser" is-config="true" duration-ms="1010" started-at="2020-05-03T01:26:30 EDT" finished-at="2020-05-03T01:26:31 EDT">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeBrowser -->
        <test-method status="PASS" signature="createDriverInstance(java.lang.String)[pri:0, instance:test.testCases.retryFailedDemo@1dac5ef]" name="createDriverInstance" is-config="true" duration-ms="4606" started-at="2020-05-03T01:26:31 EDT" finished-at="2020-05-03T01:26:35 EDT">
          <params>
            <param index="0">
              <value>
                <![CDATA[chrome]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- createDriverInstance -->
        <test-method status="FAIL" signature="testF3()[pri:0, instance:test.testCases.retryFailedDemo@1dac5ef]" name="testF3" duration-ms="3" started-at="2020-05-03T01:26:35 EDT" finished-at="2020-05-03T01:26:35 EDT">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [false] but found [true]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [false] but found [true]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.failNotEquals(Assert.java:969)
at org.testng.Assert.assertFalse(Assert.java:65)
at org.testng.Assert.assertFalse(Assert.java:75)
at test.testCases.retryFailedDemo.testF3(retryFailedDemo.java:28)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:597)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at org.testng.TestRunner.privateRun(TestRunner.java:766)
at org.testng.TestRunner.run(TestRunner.java:587)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:28)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:425)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:68)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testF3 -->
        <test-method status="PASS" signature="closeBrowser()[pri:0, instance:test.testCases.retryFailedDemo@1dac5ef]" name="closeBrowser" is-config="true" duration-ms="849" started-at="2020-05-03T01:26:35 EDT" finished-at="2020-05-03T01:26:36 EDT">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeBrowser -->
      </class> <!-- test.testCases.retryFailedDemo -->
      <class name="test.testCases.SearchPageTestCases">
        <test-method status="PASS" signature="setupBrowser()[pri:0, instance:test.testCases.SearchPageTestCases@77f80c04]" name="setupBrowser" is-config="true" duration-ms="18" started-at="2020-05-03T01:25:15 EDT" finished-at="2020-05-03T01:25:15 EDT">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setupBrowser -->
        <test-method status="PASS" signature="SetupClassPreRequisite()[pri:0, instance:test.testCases.SearchPageTestCases@77f80c04]" name="SetupClassPreRequisite" is-config="true" duration-ms="9" started-at="2020-05-03T01:25:15 EDT" finished-at="2020-05-03T01:25:15 EDT">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- SetupClassPreRequisite -->
        <test-method status="PASS" signature="createDriverInstance(java.lang.String)[pri:0, instance:test.testCases.SearchPageTestCases@77f80c04]" name="createDriverInstance" is-config="true" duration-ms="6486" started-at="2020-05-03T01:25:15 EDT" finished-at="2020-05-03T01:25:21 EDT">
          <params>
            <param index="0">
              <value>
                <![CDATA[chrome]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- createDriverInstance -->
        <test-method status="PASS" signature="test1()[pri:0, instance:test.testCases.SearchPageTestCases@77f80c04]" name="test1" duration-ms="6327" started-at="2020-05-03T01:25:21 EDT" finished-at="2020-05-03T01:25:28 EDT">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test1 -->
        <test-method status="PASS" signature="closeBrowser()[pri:0, instance:test.testCases.SearchPageTestCases@77f80c04]" name="closeBrowser" is-config="true" duration-ms="820" started-at="2020-05-03T01:25:28 EDT" finished-at="2020-05-03T01:25:29 EDT">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeBrowser -->
      </class> <!-- test.testCases.SearchPageTestCases -->
    </test> <!-- TestOnChrome -->
  </suite> <!-- Suite -->
</testng-results>
